import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  login: React.ReactNode;
}

export default function RootLayout({
  children,
  login
}: Readonly<Props>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-zinc-50 dark:bg-black">
        <div className="relative min-h-screen flex flex-col">
          {children}
          {login}
        </div>
      </body>
    </html>
  );
}
